### ISSUE TITLE
extractor branch: unknown opcode

### ISSUE THREAD

**Issue by felipesanches** [felipesanches/Another-World-Bytecode-Interpreter#1]
When extracting resources and disassembling them, we get a few "unknown opcodes".
My feeling is that it may be a bug in the recently implemented parsing of video opcodes.

**Comment by HaronK** [comment]
If this is still actual the problem is in parsing video command 0x40. In the VM code there are several tricks with jumping instruction pointer back and it's not implemented in dumping code.

**Comment by felipesanches** [comment]
oh! So you have at least a vague idea of the actual meaning of this? I'd love to learn more about it!

**Comment by felipesanches** [comment]
hmmm... I think nowadays I got the disassembly to work perfectly. I was able to disassemble the entire bytecode and then re-assemble it into fully functional bytecode again. So I will close this issue.

**Comment by felipesanches** [comment]
@HaronK, if you are interested in this, you will probably like to see my youtube videos about it here:

https://www.youtube.com/watch?v=hFxIBoNP-_s

**Comment by felipesanches** [comment]
And also here:

https://www.youtube.com/watch?v=iWdZzkVIbSI
